module.exports = {
  extends: ['eslint:recommended', 'plugin:prettier/recommended'],
  plugins: [],
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  env: {
    browser: true,
    es6: true,
    commonjs: true,
  },
  globals: {
    process: 'readonly',
  },
  rules: {
    'no-caller': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-floating-decimal': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-lone-blocks': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'error',
    'no-proto': 'error',
    'no-return-assign': 'error',
    'no-return-await': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTernary: true,
      },
    ],
    'no-useless-concat': 'error',
    'no-void': 'error',
    'no-with': 'error',
    radix: 'error',
    'wrap-iife': ['error', 'any'],
    'no-async-promise-executor': 'error',
    'no-extra-parens': ['error', 'functions'],
    'valid-typeof': [
      'error',
      {
        requireStringLiterals: true,
      },
    ],
    'no-catch-shadow': 'error',
    'no-label-var': 'error',
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-unused-vars': [
      'error',
      {
        vars: 'local',
        args: 'none',
      },
    ],
    'no-confusing-arrow': [
      'error',
      {
        allowParens: true,
      },
    ],
    'no-useless-computed-key': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'symbol-description': 'error',
    'template-curly-spacing': 'error',
    'yield-star-spacing': ['error', 'after'],
    'array-callback-return': 'warn',
    'block-scoped-var': 'warn',
    curly: ['warn', 'multi-line'],
    'dot-location': ['warn', 'property'],
    'dot-notation': 'warn',
    eqeqeq: [
      'warn',
      'always',
      {
        null: 'ignore',
      },
    ],
    'guard-for-in': 'warn',
    'no-div-regex': 'warn',
    'no-empty-function': [
      'warn',
      {
        allow: ['arrowFunctions', 'functions', 'methods'],
      },
    ],
    'no-extra-label': 'warn',
    'no-loop-func': 'warn',
    'no-multi-spaces': 'warn',
    'no-multi-str': 'warn',
    'no-script-url': 'warn',
    'no-unmodified-loop-condition': 'warn',
    'no-useless-call': 'warn',
    'no-useless-return': 'warn',
    'vars-on-top': 'warn',
    yoda: 'warn',
    'no-inner-declarations': 'warn',
    'no-template-curly-in-string': 'warn',
    'no-undef-init': 'warn',
    'no-useless-constructor': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': [
      'warn',
      {
        destructuring: 'all',
        ignoreReadBeforeAssign: true,
      },
    ],
    'prefer-spread': 'warn',
    'rest-spread-spacing': 'warn',
    'no-console': 'off',
  },
  overrides: [
    {
      files: ['*.test.ts', '*.test.tsx', '*.test.js', '*.test.jsx'],
      env: {
        jest: true,
      },
    },
  ],
}
